### ISSUE TITLE
[Feature Request] Correlated errors in X- and Y-

### ISSUE THREAD

**Issue by evangroopman** [dokester/BayesicFitting#17]
Hello, Do.

I just came across your very nice package and paper, and am still digesting the large amount of material here. In my main field, mass spectrometry, it often happens that we need to fit data with correlated errors in X and Y, such as a 3-isotope plot of X/Z vs. Y/Z, where X, Y, and Z are isotopes of the same element. For linear fits there are simple equations to find the best fit line, as described by York & Evensen (2004) https://doi.org/10.1119/1.1632486, but the situation is more complicated for higher order polynomials, exponentials, and the like.

I looked at your ErrorsInXandYProblem, but it seems that the weights are only defined in the Y-direction. Would you have any thoughts regarding the implementation of a method that accepts X-weights and correlations between X- and Y-uncertainties?

Thank you.

**Comment by dokester** [comment]
When we fit a straight line f(x:p) = p0 + p1 * x to data (x,y), we calculate the distances d_k = y_k - f(x_k:p) and minimise the sum over d_k for the value of p0 and p1. All well-known least squares. For maximum likelihood, the exp( -0.5 Sum( d_k )) is maximised, which is essentially the same thing, and for Bayesian fitting, the result is a distribution of the two parameters, again peaking at the same values.

This all assumes that there are only errors in the y direction. The x's are known without errors, or at least an order smaller.
When the errors on both directions are comparable in size, we still need to calculate the distances, now in 2 dimensions. 

d^2 = ( x - u )^2 + ( y - f(u:p) )^2

where u is the projection of the point  (x,y) on the line. The point on the line nearest to (x,y). We minimise circles touching the line. 
When the errors in x and y have different scale (globally or individually), we need to divide the distances in x and y by their scale values.

d^2 = (( x - u ) / sx )^2 + (( y - f(u:p)) / sy )^2

In stead of minimising circles, we minimised ellipses with axes (sx,xy) that touch the line.
One step further when the errors are correlated, the ellipses need to be rotated according to the covariance matrix of the errors (sx,sy).   

It all can be done, but it is quite nasty algebra.

Coming back to your question about ErrorsInXandYProblems, the x errors need to be encoded in the Priors on the nuisance parameters. Upon initialisation of ErrorsInXandYProblem you can give a keyword prior=GaussPrior( scale=1/x_error**2 )

In the present version of BayesicFitting only one prior can be given for that is valid for all nuisance parameters, and  you need to know the x-errors quite well.

So that leaves 3 things for me to do.
1. Expand the possible number of priors in ErrorsInXandYProblem so that errors can be presented on individual points.
2. Scale the nuisance priors with the scale in the ErrorDistribution. That way only the ratio between the errors in x and y is needed.
3. Consider how to implement correlated errors.
4. Maybe implement errors in x and y also for least squares and maxlikelihood.

**Comment by dokester** [comment]
After a nights sleep I realised that my advise to encode the x-erros into the priors of the nuisance parameters, is nonsense. It cannot be done that way. I have to adapt ErrorsInXanYProblem to weigh the x-errors and y-errors separately. Sorry.

**Comment by evangroopman** [comment]
Thanks for your thoughts. I agree, I think the errors would have to be done separately with an additional term to subtract whatever correlation there is between the weights.

**Comment by dokester** [comment]
It took quite a while to figure out how to implement it and how to weave it into the existing code. I hope I did not break things. All my test harnesses still work, but the package is so complicated that that in itself is no guarantee.
Anyway, Please let me know if something is broken. I try to fix it asap.

I wrote a not on how to implement accuracies in y, or in x and y, or even correlated. You can fine it [here](https://bayesicfitting.nl), click left first on "notes" and then on "Data Quality".

**Comment by dokester** [comment]
Closed

**Comment by evangroopman** [comment]
Thanks! I'm looking forward to exploring this.
