### ISSUE TITLE
Tag style issue with v.3.2.1 

### ISSUE THREAD

**Issue by Hellseher** [dokester/BayesicFitting#23]
Hi,

While refreshing astronomical packages for Guix, I encountered an issue
where the recently applied tag `v.3.2.1` does not style others, causing problems
with refreshing the version downstream.

I wondering if it may updated?

Thanks,
Oleg

**Comment by dokester** [comment]
Dear Oleg,

Can you be more specific on what the problem is. I will be happy to address it if I know what is wrong.

Last few days I have been busy to explore if I can build a BayesicFitting website on dokester.github.io/bayesicfitting. And I find it very confusing. So have been quite busy uploading stuff, however never publishing it. Could that have anything to do with your problems.

The published version v.3.2.1 is at pypi.org/project/bayesicfitting.

Do Kester.

**Comment by Hellseher** [comment]
Hello @dokester ,

Thank you for a very quick resopse.

The problem is not of high importance but more related to automated update
process Guix uses.

If we list all availalbe tags of the projects:
```
~/code/BayesicFitting: git tag --list | sort -rn
2.8.0
2.7.2
2.7.1
2.7.0
2.6.1
2.6.0
2.4.4
v.3.2.1
v3.2.0
v3.1.1
v3.1.0
v3.0.1
v3.0.0
V2.8.1
v2.6.2
V2.5.3
V2.5.2
V2.5.1
V2.5.0
v2.4.3
v2.4.2
v2.3.0
v2.2.1
```
You may see that the version styling is drifting a bit and the latest one -
`v.3.2.1` contains extra `.` (dot) after `v` symbol.

Thanks,
Oleg

**Comment by dokester** [comment]
OK, I see what you mean. Part of the problem is that you don't see what you have done for earlier tags. So I tend to reinvent the wheel each time I issue a new one. Do you want me to do something about it (I don't know if I can...) or is it good enough if I don't invent more kinds of wheel.
I will at least write in my notes on how to make a new release that I need to stick to one version style.

Sorry for making your life harder.
Do.

**Comment by Hellseher** [comment]
Hi,

I've made a comment on upcoming updates, I thinkg it may be left as it is, the package is already released to PyPI.

GitHub supports tag modification by the way https://docs.github.com/en/desktop/managing-commits/managing-tags-in-github-desktop

Regards,
Oleg

**Comment by dokester** [comment]
Thanks for closing
